//alert("test");
$(document).ready(function(){
$("#show_1").click(function(){
$("#car_1_text").show();
$("#show_1").hide();
$("#hide_1").show();
});
$("#hide_1").click(function(){
$("#car_1_text").hide();
$("#show_1").show();
$("#hide_1").hide();
});
$("#show_2").click(function(){
$("#car_2_text").show();
$("#show_2").hide();
$("#hide_2").show();
});
$("#hide_2").click(function(){
$("#car_2_text").hide();
$("#show_2").show();
$("#hide_2").hide();
});
$("#show_3").click(function(){
$("#car_3_text").show();
$("#show_3").hide();
$("#hide_3").show();
});
$("#hide_3").click(function(){
$("#car_3_text").hide();
$("#show_3").show();
$("#hide_3").hide();
});
});